# Generated by Django 5.2.1 on 2025-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'دیدن صفحه خانه داشبورد'), ('view_data', 'دیدن داده ها در داشبورد'), ('CKeditor_Uplode_Blog_image', 'آپلود عکس در پست بلاگ و... با ادیتور'), ('CKeditor_Uplode_Product_image', 'آپلود عکس در توضیحات محصولات با ادیتور')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
