# Generated by Django 5.2.1 on 2025-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلا: instagram, telegram channel, ...', max_length=255, unique=True, verbose_name='نام')),
                ('value', models.CharField(blank=True, help_text='مثلا: SeedHosein0', max_length=1000, verbose_name='اطلاعات')),
            ],
            options={
                'verbose_name': 'اطلاعات فروشگاه',
                'verbose_name_plural': 'اطلاعات فروشگاه',
            },
        ),
    ]
