# Generated by Django 5.2.1 on 2025-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='corepermissions',
            options={'managed': False, 'permissions': [('view_dashboard', 'Can view the dashboard home page'), ('view_data', 'Can view the data in the dashboard')]},
        ),
    ]
