# Generated by Django 5.2.1 on 2025-07-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinformation',
            name='name',
            field=models.CharField(help_text='مثلا: instagram, telegram-channel, ...', max_length=255, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='value',
            field=models.CharField(blank=True, help_text='مثلا: SeedHosein0', max_length=1000, verbose_name='مقدار'),
        ),
    ]
