# Generated by Django 5.2.1 on 2025-06-03 23:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, help_text='این نامک در URL صفحه استفاده میشود. فقط از حروف، اعداد، خط تیره و زیرخط استفاده کنید.', max_length=220, unique=True, verbose_name='نامک (Slug)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوای صفحه')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه ایستا',
                'verbose_name_plural': 'صفحات ایستا',
                'ordering': ['title'],
            },
        ),
    ]
