# Generated by Django 5.2.1 on 2025-06-03 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('timestamp',), 'verbose_name': 'پیام گفتگو', 'verbose_name_plural': 'پیام\u200cهای گفتگو'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ('-created_at',), 'verbose_name': 'جلسه گفتگو', 'verbose_name_plural': 'جلسات گفتگو'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read_by_agent',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط پشتیبان'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read_by_user',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='جلسه گفتگو'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='مهر زمانی'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل مهمان'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='support_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
