# Generated by Django 5.2.1 on 2025-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='ضروری. فرمت: name@domain.com', max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='گروه\u200cهایی که این کاربر به آن\u200cها تعلق دارد. یک کاربر تمام مجوزهای اعطا شده به هر یک از گروه\u200cهای خود را دریافت خواهد کرد.', related_name='user_profile_groups', related_query_name='user_profile', to='auth.group', verbose_name='گروه\u200cها'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text='ضروری. فرمت: 09xxxxxxxxx یا +989xxxxxxxxx', max_length=15, unique=True, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='مجوزهای خاص برای این کاربر.', related_name='user_profile_permissions', related_query_name='user_profile', to='auth.permission', verbose_name='مجوزهای کاربر'),
        ),
    ]
