# Generated by Django 5.2.1 on 2025-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='. فرمت: name@domain.com', max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='. فرمت: 09xxxxxxxxx یا +989xxxxxxxxx', max_length=15, unique=True, verbose_name='شماره تلفن همراه'),
        ),
    ]
