# Generated by Django 5.2.1 on 2025-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='. فرمت: name@domain.com', max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='. فرمت: 09xxxxxxxxx یا +989xxxxxxxxx', max_length=15, null=True, unique=True, verbose_name='شماره تلفن همراه'),
        ),
    ]
