# Generated by Django 5.2.1 on 2025-12-30 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='. فرمت: 09xxxxxxxxx یا +989xxxxxxxxx', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+989\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
