# Generated by Django 5.2.1 on 2025-06-01 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی وبلاگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ (نامک)')),
            ],
            options={
                'verbose_name': 'دسته بندی وبلاگ',
                'verbose_name_plural': 'دسته بندی های وبلاگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پست')),
                ('slug', models.SlugField(allow_unicode=True, help_text='به صورت خودکار از عنوان ساخته میشود.', max_length=255, unique=True, verbose_name='اسلاگ (نامک)')),
                ('content', models.TextField(verbose_name='محتوای پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر شاخص پست')),
                ('tags', models.CharField(blank=True, help_text='کلمات کلیدی را با کاما (,) جدا کنید.', max_length=255, verbose_name='برچسب ها')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست های وبلاگ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام (برای مهمانان)')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل (برای مهمانان, نمایش داده نمیشود)')),
                ('comment', models.TextField(verbose_name='متن دیدگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت دیدگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت دیدگاه')),
                ('admin_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط ادمین')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (اگر عضو باشد)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='پست مربوطه')),
            ],
            options={
                'verbose_name': 'دیدگاه وبلاگ',
                'verbose_name_plural': 'دیدگاه های وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
