# Generated by Django 5.2.1 on 2026-01-04 16:00

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'دسته بندی وبلاگ', 'verbose_name_plural': 'دسته بندی های وبلاگ'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='level',
            field=models.PositiveIntegerField(editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.blogcategory', verbose_name='دسته والد'),
        ),
    ]
