# Generated by Django 5.2.1 on 2025-06-03 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Discount Name')),
                ('code', models.CharField(help_text='e.g., SUMMER20, SAVE10000', max_length=50, unique=True, verbose_name='Discount Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=2, help_text='If percentage, enter as a number (e.g., 10 for 10%). If fixed amount, enter the monetary value.', max_digits=10, verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('min_cart_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total amount in cart for this discount to be applicable.', max_digits=12, null=True, verbose_name='Minimum Cart Amount')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('products', models.ManyToManyField(blank=True, related_name='campaigns', to='products.product', verbose_name='Associated Products')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
    ]
