# Generated by Django 5.2.1 on 2025-06-03 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_and_campaigns', '0001_initial'),
        ('products', '0002_alter_product_description_full'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'کمپین', 'verbose_name_plural': 'کمپین\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-start_date'], 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='products.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(help_text='مثال: SUMMER20, SAVE10000', max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed_amount', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_cart_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='حداقل مبلغ کل در سبد خرید برای اعمال این تخفیف.', max_digits=12, null=True, verbose_name='حداقل مبلغ سبد خرید'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='اگر درصدی است، عدد را وارد کنید (مثلاً 10 برای 10%). اگر مبلغ ثابت است، ارزش پولی را وارد کنید.', max_digits=10, verbose_name='مقدار'),
        ),
    ]
