# Generated by Django 5.2.1 on 2025-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(max_length=800, verbose_name='متن نظر'),
        ),
    ]
