# Generated by Django 5.2.1 on 2025-06-01 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل (تومان)')),
                ('billing_name', models.CharField(max_length=255, verbose_name='نام صورتحساب')),
                ('billing_address', models.TextField(verbose_name='آدرس صورتحساب')),
                ('billing_city', models.CharField(max_length=100, verbose_name='شهر صورتحساب')),
                ('billing_postal_code', models.CharField(max_length=20, verbose_name='کد پستی صورتحساب')),
                ('billing_phone', models.CharField(max_length=15, verbose_name='تلفن صورتحساب')),
                ('shipping_name', models.CharField(max_length=255, verbose_name='نام تحویل گیرنده')),
                ('shipping_address', models.TextField(verbose_name='آدرس تحویل')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='شهر تحویل')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='کد پستی تحویل')),
                ('shipping_phone', models.CharField(max_length=15, verbose_name='تلفن تحویل')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='روش پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مشتری')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت در زمان خرید (تومان)')),
                ('product_name_at_purchase', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام محصول در زمان خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_and_orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مورد سفارش',
                'verbose_name_plural': 'موارد سفارش',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('is_saved_for_later', models.BooleanField(default=False, verbose_name='ذخیره برای بعد؟')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_and_orders.cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مورد سبد خرید',
                'verbose_name_plural': 'موارد سبد خرید',
                'unique_together': {('cart', 'product', 'is_saved_for_later')},
            },
        ),
    ]
