# Generated by Django 5.2.1 on 2025-06-03 23:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات کامل / نقد و بررسی'),
        ),
    ]
