# Generated by Django 5.2.1 on 2025-07-22 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_description_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='category_images/', verbose_name='تصویر دسته'),
            preserve_default=False,
        ),
    ]
