# Generated by Django 5.2.1 on 2025-07-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت جایگزین (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attribute_values', models.ManyToManyField(related_name='variants', to='products.productattributevalue', verbose_name='مقادیر ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول اصلی')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع های محصول',
            },
        ),
    ]
