# Generated by Django 5.2.1 on 2025-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(auto_created=True, default="0", max_length=100, unique=True, verbose_name='SKU'),
            preserve_default=False,
        ),
    ]
