# Generated by Django 5.2.1 on 2025-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='SKU'),
        ),
    ]
