# Generated by Django 5.2.1 on 2025-07-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع های محصولات'},
        ),
    ]
