# Generated by Django 5.2.1 on 2025-07-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='products.productattributevalue', verbose_name='مقادیر ویژگی'),
        ),
    ]
