# Generated by Django 5.2.1 on 2025-07-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productvariant_attribute_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', to='products.productattributevalue', verbose_name='مقادیر ویژگی'),
        ),
    ]
