# Generated by Django 5.2.1 on 2025-07-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productvariant_attribute_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='sku',
            new_name='_sku',
        ),
    ]
