# Generated by Django 5.2.1 on 2025-08-31 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename__sku_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.productattributevalue', verbose_name='مشخصات فنی'),
        ),
    ]
