# Generated by Django 5.2.1 on 2025-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_attribute_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productattributevalue', verbose_name='مشخصات فنی'),
        ),
    ]
